apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nps-authsvc-hpa
  namespace: blue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authSvc
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
      
---

# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: nps-authsvc-hpa
#   namespace: green
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: authSvc
#   minReplicas: 2
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 75